### ISSUE TITLE
Doesn't run when navigating

### ISSUE THREAD

**Issue by j4k0xb** [SavageCore/github-comment-view-source#3]
GitHub edits the html dynamically instead of refreshing the page, so the userscript doesn't run in many cases

1. Visit https://github.com/SavageCore/github-comment-view-source/issues
2. Click on any issue

No view source button is added:
![image](https://github.com/SavageCore/github-comment-view-source/assets/55899582/979309c2-f957-49fd-9acc-068c6a34ae28)

**Comment by SavageCore** [comment]
Thanks, can't believe I missed this!
